


name: Create Release

on:
  release:
    types: [published]
    

jobs:
  build_with_pyinstaller:
    
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Compile to .exe with Pyinstaller
        shell: bash
        run: |
          pyinstaller --clean --noconfirm --onefile --console "MaxShot.py"
          chown -R --reference=./dist
